"""Short calculus / JVP references for each ``print(@…)`` golden case.

Used by ``scripts/test_print_at.py --report`` and coverage tests.  Strings are
plain-text math meant for human review, not symbolic verification.
"""

from __future__ import annotations

from typing import Dict

GOLDEN_CALCULUS: Dict[str, str] = {
    "constant": "y independent of x ⇒ ∂y/∂x = 0.",
    "identity": "y = x ⇒ dy = dx (JVP: @y = @x).",
    "add": "y = x + x ⇒ dy/dx = 2.",
    "sub": "y = x − c ⇒ dy = dx.",
    "product": "y = x² ⇒ dy = 2x dx.",
    "product_two_vars": "y = ab ⇒ dy = a db + b da.",
    "quotient": "y = a/b ⇒ dy = (b da − a db) / b².",
    "power_const": "y = x^n ⇒ dy = n x^(n−1) dx.",
    "power_square": "y = x² ⇒ dy = 2x dx.",
    "neg": "y = −x ⇒ dy = −dx.",
    "chain_let": "z = x², y = 2z ⇒ dz = 2x dx, dy = 2 dz.",
    "exp_scalar": "y = e^x ⇒ dy = e^x dx.",
    "exp_einstein": "e[i] = exp(x[i]) ⇒ @e[i] = exp(x[i]) @x[i] (elementwise).",
    "sum_reduction": "s = Σ_k exp(x[k]) ⇒ ∂s/∂x_i = exp(x_i); with intermediate e, @s = Σ @e.",
    "softmax_quotient": "y[i] = e[i]/s, s = Σ e[k]; quotient + sum rule ⇒ @y[i] = (s @e[i] − e[i] @s)/s².",
    "if_else": "Piecewise: y = x if x>0 else 0 ⇒ dy = dx on active branch, 0 else.",
    "scalar_mul": "y = c x ⇒ dy = c dx.",
    "compound": "y = (x+1)*(x+2); product + chain rules.",
    "call_plus_fn": "y = x + f(x); with f(t)=t+1 inlined, f'=1 ⇒ @y = 2 @x (generic rule would be @y = @x + @f).",
    "multistatement_callee_g": "g(t)=2(t+1); y=g(x) ⇒ chain rule through internal lets.",
    "log_scalar": "y = ln x ⇒ dy = dx / x.",
    "sin_scalar": "y = sin x ⇒ dy = cos x dx.",
    "cos_scalar": "y = cos x ⇒ dy = −sin x dx.",
    "tan_scalar": "y = tan x ⇒ dy = sec² x dx.",
    "log1p_scalar": "y = ln(1+x) ⇒ dy = dx / (1+x).",
    "expm1_scalar": "y = e^x − 1 ⇒ dy = e^x dx.",
    "atan_scalar": "y = arctan x ⇒ dy = dx / (1+x²).",
    "asin_scalar": "y = arcsin x ⇒ dy = dx / √(1−x²).",
    "acos_scalar": "y = arccos x ⇒ dy = −dx / √(1−x²).",
    "atan2_two_vars": "z = atan2(y,x) ⇒ ∂z/∂y = x/(x²+y²), ∂z/∂x = −y/(x²+y²).",
    "tanh_scalar": "y = tanh x ⇒ dy = sech² x dx (here via stable exp form).",
    "sinh_scalar": "y = sinh x ⇒ dy = cosh x dx (piecewise exp for stability).",
    "cosh_scalar": "y = cosh x ⇒ dy = sinh x dx.",
    "asinh_scalar": "y = asinh x ⇒ dy = dx / √(1+x²) (algebraic form in IR).",
    "acosh_scalar": "y = acosh x ⇒ dy = dx / √(x²−1) (x>1).",
    "atanh_scalar": "y = artanh x ⇒ dy = dx / (1−x²) (chain on log form in IR).",
    "erf_scalar": "y = erf(x) (A&S primal in stdlib); JVP is @fn rule ∂y/∂x = (2/√π) e^(−x²) dx.",
    "abs_scalar": "y = |x| ⇒ dy = sign(x) dx (0 subgradient choice at 0).",
    "sign_scalar": "y = sign(x) ⇒ dy = 0 off 0 (subgradient).",
    "min_scalar": "y = min(x,c) ⇒ dy = dx on x<c, 0 on x>c.",
    "max_scalar": "y = max(x,0) ⇒ dy = dx on x>0, 0 on x<0.",
    "reciprocal_scalar": "y = 1/x ⇒ dy = −dx / x².",
    "rsqrt_scalar": "y = x^(−1/2) ⇒ dy = -(1/(2*x^(3/2))) dx = -0.5*x^(−3/2) dx.",
    "sqrt_via_pow": "y = x^0.5 ⇒ dy = (1/(2*sqrt(x))) dx = 0.5*x^(−0.5) dx.",
    "mod_scalar": "y = a % b with b fixed ⇒ ∂y/∂a = 1 a.e. (piecewise).",
    "quotient_chain": "Nested quotients; quotient + chain rules.",
    "einstein_square": "y[i] = x[i]² ⇒ @y[i] = 2 x[i] @x[i].",
    "prod_reduction": "For y = Π_j x_j, ∂y/∂x_i = Π_{j!=i} x_j = y/x_i when x_i != 0; quotient result keeps x's shape.",
    "reduce_sum": "Row sum of x ⇒ each @output[batch] = Σ_j @x[batch,j].",
    "reduce_l1": "Σ_j |x_j|; ∂/∂x_j = sign(x_j) (JVP: Σ sign(x)·@x).",
    "reduce_sum_square": "Σ x² ⇒ ∂/∂x_ij = 2 x_ij.",
    "reduce_mean": "For y[batch] = (1/n) Σ_j x[batch,j], ∂y[batch]/∂x[batch,j] = 1/n; the row cotangent is distributed uniformly across the reduced axis.",
    "linear": "y[b,j] = Σ_k W[j,k] x[b,k] + b[j] ⇒ matrix-vector product rule per row.",
    "mse_loss": "PyTorch/Flux mean-squared error: L = mean((pred−target)^2). For N reduced elements, ∂L/∂pred = 2(pred−target)/N and ∂L/∂target = -2(pred−target)/N.",
    "mae_loss": "PyTorch L1 / Flux MAE with mean aggregation: L = mean(|pred−target|). For N reduced elements, ∂L/∂pred = sign(pred−target)/N (subgradient 0 at equality).",
    "huber_loss": "Smooth L1: quadratic inside |r|≤δ, linear outside; d|r| = sign(r) dr (@fn abs) in linear branch.",
    "binary_cross_entropy": "Mean binary cross-entropy with clamped p: L = mean(-(t log p + (1−t) log(1−p))). For N reduced elements, ∂L/∂p = (-t/p + (1−t)/(1−p)) / N on unclamped entries.",
    "softmax": "y_i = exp(z_i)/Σ exp(z_k); ∂y_i/∂z_j = y_i (δ_ij − y_j) (stable z = x − max).",
    "log_softmax": "ℓ_i = x_i - log(Σ_k exp(x_k)); ∂ℓ_i/∂x_j = δ_ij - softmax_j. Same-rank tensor quotients follow the full log-softmax Jacobian action.",
    "reduce_l2": "‖x‖_2 ⇒ ∂/∂x = x/‖x‖.",
    "reduce_log_sum": "log(Σ x) ⇒ ∂/∂x_i = 1/(Σ x).",
    "reduce_log_sum_exp": "log Σ exp(x) (log-sum-exp); ∂/∂x_i = softmax_i.",
    "cosine_similarity": "For each retained batch index b, c_b = <a_b,b_b>/(||a_b|| ||b_b||); ∂c_b/∂a_b = b_b/(||a_b|| ||b_b||) - c_b a_b/||a_b||^2, and symmetrically for b.",
    "matmul": "C[i,j] = Σ_k A[i,k] B[k,j] ⇒ @C[i,j] = Σ_k (A[i,k] @B[k,j] + B[k,j] @A[i,k]).",
    "max_pool": "y[b,c,oh,ow] = max over window of x; JVP routes ∂ only through entries that attain the max (subgradient of max). print(@…) expands std::ml::max_pool callee (rank-dispatch in primal).",
    "max_pool_relu_arg": "y = max_pool(relu(x)); JVP combines ReLU's active-set mask with max-pool argmax routing, so only entries that are both positive and selected by the window max receive cotangent flow.",
    "mnist_conv2d": "MNIST-shaped 2D conv as Einstein: y[b,co,i,j]=Σ_{c,m,n} x[b,c,i+m,j+n] w[co,c,m,n]+b[co]; @y is sum-of-products rule (∂/∂w: x factor, ∂/∂x: w factor, ∂/∂b: 1) — same calculus as std::ml::conv2d inner sum.",
    "batch_matmul": "Same as matmul per batch slice b: @C[b,i,j] = Σ_k (A[b,i,k] @B[b,k,j] + B[b,k,j] @A[b,i,k]).",
    "relu": "y = max(0,x) ⇒ dy = dx if x>0 else 0.",
    "sigmoid": "σ(x) = 1/(1+e^(−x)) ⇒ σ' = σ(1−σ).",
    "leaky_relu": "y = x if x>0 else α x ⇒ piecewise 1 or α.",
    "elu": "y = x if x>0 else α(e^x−1) ⇒ 1 or α e^x.",
    "swish": "y = x σ(x) ⇒ product + σ' term.",
    "softsign": "y = x/(1+|x|) ⇒ quotient rule with d|x| = sign(x) dx (@fn abs).",
    "hardtanh": "clip to [−1,1] ⇒ derivative 1 inside, 0 outside.",
    "relu6": "min(max(x,0),6) ⇒ piecewise 1 on (0,6), else 0.",
    "prelu": "like leaky_relu with learned α.",
    "elu_alpha": "ELU with parameter α.",
    "celu": "continuously differentiable ELU variant.",
    "softshrink": "shrink toward zero by λ; derivative 1 outside ±λ, 0 inside.",
    "hardshrink": "0 if |x|≤λ else x; derivative via |x| and thresholds.",
    "threshold": "y = x if x>θ else v; piecewise.",
    "hardswish": "x * ReLU6(x+3)/6; product + ReLU6 branches.",
    "thresholded_relu": "ReLU with threshold θ.",
    "selu": "scaled ELU with fixed λ, α.",
    "hardsigmoid": "piecewise linear clamp of (x+3)/6.",
    "softplus": "softplus(x) = log(1+e^x); exact derivative is sigmoid(x). In the stabilized implementation, the large-x linear branch has derivative 1, matching sigmoid(x) -> 1.",
    "gelu": "x Φ(x) (approx); product + tanh-inner derivative in implementation.",
    "mish": "x tanh(softplus(x)); product + chain.",
    "tanhshrink": "x − tanh x ⇒ @y = @x − sech² x @x.",
}
